[package]
name = "hexx"
version = "0.1.0"
edition = "2021"
authors = ["Felix de Maneville <felix.maneville@gmail.com>"]
description = "Hexagonal utilities"
license = "Apache-2.0"
keywords = ["hexagon", "bestagon", "bevy", "geometry"]
categories = ["game-development", "mathematics"]
repository = "https://github.com/ManevilleF/hexx"
exclude = [".github"]

[features]
default = []
# serde compatibility
ser_de = ["serde", "glam/serde"]

[dependencies]
glam = "0.22"
itertools = "0.10"

[dependencies.serde]
version = "1"
default-features = false
features = ["derive"]
optional = true

# For lib.rs doctests and examples
[dev-dependencies.bevy]
version = "0.9"
features = ["render", "bevy_asset", "bevy_winit"]
default-features = false

[[examples]]
name = "hex_grid"
path = "examples/hex_grid"
