[package]
name = "hexx"
version = "0.1.0"
edition = "2021"
authors = ["Felix de Maneville <felix.maneville@gmail.com>"]
description = "Hexagonal utilities"
license = "Apache License 2.0"
keywords = ["hexagon", "bestagon", "bevy", "geometry"]
categories = ["game-development", "mathematics"]
repository = "https://github.com/ManevilleF/hexx"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
glam = "0.21"
itertools = "0.10"

# For lib.rs doctests
[dev-dependencies.bevy]
version = "0.8"
features = ["render"]
default-features = false
